package play.gradle

import org.gradle.testkit.runner.GradleRunner
import java.io.File

/**
 * Shared helpers for the TestKit functional tests. Each test builds a temporary
 * consumer project under a JUnit @TempDir, applies the Play1 plugin via
 * withPluginClasspath() (the classpath generated by java-gradle-plugin), and
 * runs real Gradle invocations against it.
 */
object TestProject {

    /**
     * Write a minimal consumer project into [dir]: a settings.gradle.kts and a
     * build.gradle.kts that applies id("org.playframework.play1"). [play1Block]
     * is the body of the play1 { } configuration block (may be empty).
     *
     * The plugin applies the `java` plugin and pins a Java 25 toolchain, so the
     * consumer build needs a settings name; no source dirs are required for the
     * tasks under test (none compile or fork a JVM here).
     */
    fun write(dir: File, play1Block: String = "") {
        File(dir, "settings.gradle.kts").writeText(
            """
            rootProject.name = "testapp"
            """.trimIndent() + "\n"
        )
        File(dir, "build.gradle.kts").writeText(
            """
            plugins {
                id("org.playframework.play1")
            }

            play1 {
            $play1Block
            }
            """.trimIndent() + "\n"
        )
    }

    fun runner(dir: File, vararg args: String): GradleRunner =
        GradleRunner.create()
            .withProjectDir(dir)
            .withPluginClasspath()
            // TestKit reuses a long-lived test daemon by default; the consumer
            // builds here are configuration-only, but pinning --no-configuration-cache
            // keeps task-graph assertions (tasks --all) deterministic across runs.
            .withArguments(*args)
            .forwardOutput()
}
