plugins {
    `kotlin-dsl`
    `java-gradle-plugin`
    `maven-publish`
}

// Group + version are inherited from the root project, which derives version
// from framework/build.xml's baseversion (single source of truth).
group = "org.playframework"
version = rootProject.version

repositories {
    mavenCentral()
}

dependencies {
    // gradleTestKit() provides GradleRunner. java-gradle-plugin auto-generates
    // the plugin-under-test metadata, so withPluginClasspath() injects the
    // plugin with no manual classpath wiring (PF-139).
    testImplementation(gradleTestKit())
    testImplementation("org.junit.jupiter:junit-jupiter:6.1.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

gradlePlugin {
    plugins {
        register("play1") {
            id = "org.playframework.play1"
            implementationClass = "play.gradle.Play1Plugin"
            displayName = "Play 1 Gradle Plugin"
            description = "Builds and runs Play Framework 1.x applications via Gradle"
        }
    }
}

// Publish into a flat Maven repo under the framework distribution. Apps
// generated by playNewApp reference this repo from pluginManagement.repositories,
// so they resolve id("org.playframework.play1") without needing to compile
// the plugin from source via includeBuild() — that model breaks on read-only
// installs (e.g. /opt/play1 owned by root) because compiling the plugin writes
// into the included build's gradle-plugin/build/ directory.
publishing {
    repositories {
        maven {
            name = "FrameworkLocal"
            url = uri(rootProject.layout.projectDirectory.dir("framework/gradle-plugin-repo"))
        }
    }
}
