plugins {
    `kotlin-dsl`
    `java-gradle-plugin`
    `maven-publish`
}

// Group + version are inherited from the root project, which derives version
// from framework/build.xml's baseversion (single source of truth).
group = "org.playframework"
version = rootProject.version

repositories {
    mavenCentral()
}

gradlePlugin {
    plugins {
        register("play1") {
            id = "org.playframework.play1"
            implementationClass = "play.gradle.Play1Plugin"
            displayName = "Play 1 Gradle Plugin"
            description = "Builds and runs Play Framework 1.x applications via Gradle"
        }
    }
}

// Publish into a flat Maven repo under the framework distribution. Apps
// generated by playNewApp reference this repo from pluginManagement.repositories,
// so they resolve id("org.playframework.play1") without needing to compile
// the plugin from source via includeBuild() — that model breaks on read-only
// installs (e.g. /opt/play1 owned by root) because compiling the plugin writes
// into the included build's gradle-plugin/build/ directory.
publishing {
    repositories {
        maven {
            name = "FrameworkLocal"
            url = uri(rootProject.layout.projectDirectory.dir("framework/gradle-plugin-repo"))
        }
    }
}
