name: Check

on:
  pull_request: # Check Pull Requests

  push:
    branches:
      - main # Check branch after merge

env:
  DEFAULT_JAVA_VERSION: '25'

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  testing:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        jdk: [ 25 ]
        os: [ubuntu-latest, windows-latest]
        include:
          - target: 25
            jdk: 25

    name: Build / Tests -> JDK-${{ matrix.jdk }}/ Target java-${{ matrix.target }} / ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Set up python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'

      - name: Build with Ant
        working-directory: ./framework
        run: ant test -Dbuild-release=${{ matrix.target }}

  build:
    needs:
      - testing
    runs-on: ubuntu-latest
    name: BUILD ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Set up python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Set up JDK ${{ env.DEFAULT_JAVA_VERSION }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.DEFAULT_JAVA_VERSION }}
          distribution: 'adopt'

      - name: Build with Ant
        working-directory: ./framework
        run: ant artifact -Dbuild-release=${{ env.DEFAULT_JAVA_VERSION }}

      - name: Zipping artifact
        uses: actions/upload-artifact@v7
        with:
          name: play-${{ github.sha }}
          if-no-files-found: error
          path: |
            ./framework/dist/*

  # Specific build on mac because of issue with firephoque browser (FIXME)
  build-on-mac:
    runs-on: ${{ matrix.os }}
    name: Build -> JDK-${{ matrix.jdk }}/ Target java-${{ matrix.target }} / ${{ matrix.os }}
    strategy:
      matrix:
        jdk: [ 25 ]
        os: [ macos-latest ]
        include:
          - target: 25
            jdk: 25

    steps:
       - name: Checkout
         uses: actions/checkout@v6
         with:
           # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
           fetch-depth: 0

       - name: Set up python 3
         uses: actions/setup-python@v6
         with:
           python-version: '3.x'
           architecture: 'x64'

       - name: Set up JDK ${{ matrix.jdk }}
         uses: actions/setup-java@v5
         with:
           java-version: ${{ matrix.jdk }}
           distribution: 'adopt'

       - name: Build with Ant
         working-directory: ./framework
         run: ant build -Dbuild-release=${{ matrix.target }}